# Generated by Django 5.0.1 on 2024-01-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sku', models.CharField(default='', max_length=8, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
