# Generated by Django 5.0.1 on 2024-01-31 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('reference', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_received', models.DateField()),
                ('qty', models.IntegerField()),
                ('supplier', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=200)),
                ('prod_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('prod_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('reference', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_shipped', models.DateField()),
                ('qty', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=200)),
                ('prod_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('prod_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
